DROP TABLE IF EXISTS incomes;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS banks;
DROP TABLE IF EXISTS balances;
DROP TABLE IF EXISTS personal_access_tokens;
DROP TABLE IF EXISTS tokos;
DROP TABLE IF EXISTS users;
